ALTER TABLE tasks ADD COLUMN IF NOT EXISTS production_shards INT NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS conveyor_mk INT NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS pipe_mk INT NOT NULL DEFAULT 0;
